### ISSUE TITLE
Context of use

### ISSUE THREAD

**Issue by Solido** [goposse/fluro#1]
Hi Luke,
I've started working on my Flutter app and GenerateRoute is not an obvious choice.
Can I start using your router which seems to be a perfect match.

Also what strategy do you advise to pass the Router to Widget ?

I'd like to see an example dir with basics use cases.

Thank you for this repo,
Robert

**Comment by lukef** [comment]
I'll add a wiki entry. You can still use the standard flutter `onGenerateRoute` with the router if you want or you can just bypass it totally. If you want to use `onGenerateRoute` with `Navigator` you can do this:

```
// some where in app initialization
Router router = new Router();
router.define("/users/:id", handler: userDetailHandler);

// in app build
return new MaterialApp(
  ...,
  onGenerateRoute: router.generator,
);
```

This will allow you to then use `Navigator.pushNamed(context, "/users/1234abcd");` out of the box.

If you don't want to use the generator then you can use `router.navigateTo(context, "/users/1234abcd");` and it will match the route and create the `MaterialPageRoute` for you.

I'll push up a description of all of this soon.

Thanks for the feedback and thanks for using our library!

**Comment by Solido** [comment]
I added this repo to https://github.com/Solido/awesome-flutter
Thanks Luke !

**Comment by lukef** [comment]
Added an example project. Also, we changed the name of the package to `fluro`. You might want to update your refs! Let me know how it all works out.
