### ISSUE TITLE
Async HandlerFunc

### ISSUE THREAD

**Issue by megamattron** [goposse/fluro#16]
On some of my routes I'd like to load some data from a server based on the ID in the URL, I was thinking of doing that via an async handler but that doesn't seem possible. Am I missing another way to do it?

Thanks!

**Comment by megamattron** [comment]
(And as soon as I posted this I realized maybe the widget itself should be doing the async operations, not the route handler. If this is the case my apologies, I'm still getting a handle on everything).

**Comment by jpgilchrist** [comment]
@megamattron I'm not a contributor to the project as I just started using it myself, but architecturally speaking the async logic you're talking about should not be done in the route handler. It should be triggered by the mounted component.

**Comment by megamattron** [comment]
Thanks @jpgilchrist, makes sense.
