### ISSUE TITLE
Screen image shifted up/left when using transitions

### ISSUE THREAD

**Issue by dresserm** [goposse/fluro#17]
I'm not sure what changed (likely a Flutter upgrade) but suddenly earlier today, routing to a screen using a Fluro transition causes the screen image to be shifted once it settles from the transition, so that the bottom left corner of the image is drawn at the center of the screen, with the remainder of the screen remaining black.

**Comment by alardizabal** [comment]
Can you update to 1.2.1? There were some breaking changes in how offsets were handled that should now be fixed. Let me know if you still see problems.

**Comment by dresserm** [comment]
Thank you!  I'll check back in when I have a chance to test the update.

On Tue, Oct 10, 2017 at 2:46 PM, Albert Lardizabal <notifications@github.com

**Comment by dresserm** [comment]
The update to 1.2.1 fixed the problems I was having.

Thank you!
