### ISSUE TITLE
Route handler is called three times

### ISSUE THREAD

**Issue by ride4sun** [goposse/fluro#20]
I use router.navigateTo(context, _routeName, transition: TransitionType.fadeIn);

My Handler is called three times. 2 times before the screen shows and than another time when I use the back button.

Route:
`
 router.define(invitePeopleScreen, handler: invitePeopleScreenHandler);
`

Handler:
`
var invitePeopleScreenHandler = new Handler(
    handlerFunc: (BuildContext context, Map<String, dynamic> params) {
      appController.changeActiveScreenState(Routes.invitePeopleScreen);
      return new InvitePeopleScreen();
    });
`

The documentation is pretty slim !!!

'

**Comment by lukef** [comment]
Logged an issue in the Flutter project here https://github.com/flutter/flutter/issues/14124.

**Comment by lukef** [comment]
This seems like it is as designed so I am closing
