### ISSUE TITLE
SlideTransition FractionalOffset usage should be changed to Offset

### ISSUE THREAD

**Issue by Hixie** [goposse/fluro#23]
See https://groups.google.com/forum/#!topic/flutter-dev/fmr-C9xK5t4

**Comment by collinjackson** [comment]
I believe this was fixed in version 1.2.0, see #18 #19

**Comment by alardizabal** [comment]
Yes, issue should be fixed. Current version is 1.2.1. I've updated master.

**Comment by lukef** [comment]
Closing as this has been fixed in 1.2.x
