### ISSUE TITLE
No registered route was found to handle '/videos/1234'.

### ISSUE THREAD

**Issue by stemuk** [goposse/fluro#26]
I tried to implement routing in my application with fluro, however I had several problems following the 'getting started' guide on Github. 

My implementation is rather simple, since the `new GestureDetector(
              onTap: () {
                _handleTap(context);
              }, .... )`
is supposed to manually push the route with `
void _handleTap(BuildContext context) {
  router.navigateTo(context, "/videos/1234",
      transition: TransitionType.native);
}`.

The router is initialized according to the getting started example, but once I test the app the error 

> No registered route was found to handle '/videos/1234'.

What else is needed in order to push the route, or am I doing something wrong?

**Comment by lukef** [comment]
Can you share the code where you register / create the routes?

**Comment by stemuk** [comment]
Yes, sure. 
```
final router = new Router();
var usersHandler = new Handler(handlerFunc: (BuildContext context, Map<String, dynamic> params) {
  return new VideosScreen(params["id"]);
});
void defineRoutes(Router router) {
  router.define("/videos/:id", handler: usersHandler);
}
void _handleTap(BuildContext context) {
  router.navigateTo(context, "/videos/1234",
      transition: TransitionType.native);
}

```

The full file is [here](https://www.pastiebin.com/5a17102ccf8d2).

**Comment by lukef** [comment]
Will take a look

**Comment by lukef** [comment]
I tested here and it seems to be working ok. But, let me shoot over some suggestions to try and if it doesn't work we can take another look. 

If you're only using one router in your app (which probably most people do) you can try creating a class specifically for routing responsibilities. For example:

```dart
import 'package:fluro/fluro.dart';
import 'package:nativedemo/routing/handlers/product_handlers.dart';

class AppRouter {

  static final AppRouter _instance = new AppRouter._internal();
  final Router _router = new Router();  // global router

  factory AppRouter() {
    return _instance;
  }
  AppRouter._internal();

  // singleton
  Router router() { return _router; }

  void configureRoutes() {
    _router.define("/videos/:id", handler: videoDetailHandler);
  }
}
```

Then inside your `Home` class you can add (or inside `initState` if you make it stateless):

```dart
  Home() : super() {
    final appRouter = new AppRouter();
    appRouter.configureRoutes();
    appRouter.router().printTree();
  }

```

Adding it to the constructor or `initState` will mean that it wont be re-created / reconfigured each time `build()` is called.

Finally, at the point when you want to navigate to the route you can use:

```dart
new AppRouter().router().navigateTo(context, "/videos/1234");
```

Let me know how it goes.

**Comment by stemuk** [comment]
Thanks a lot for your help, will try it out in a few hours and get back to you how it worked. Thanks again!

**Comment by stemuk** [comment]
I implemented fluro following your advice, but I still have the error "Undefined name 'context'." for the part that manually pushes the route
 
`new AppRouter().router().navigateTo(context, "/videos/1234");`

How do I define the variable and what type of parameter is required? Thanks again for your help!

**Comment by lukef** [comment]
Can you share the code again? That's almost certainly a regular dart issue. It means that `context`, as a variable, is undefined.

**Comment by stemuk** [comment]
Sure. I already expected it to be a dart issue, but I somehow am unable to fix it. The code is [here](https://www.pastiebin.com/5a197aa9dc88d), and the line in question is 69, where the 'context' in `void _handleTap() {
  new AppRouter().router().navigateTo(context, "/videos/1234");
}` seems to be undefined.

**Comment by lukef** [comment]
Your `_handleTap` method is declared at a global level and is not contained inside a class. The `BuildContext` object is not defined at that scope. You should move `_handleTap` into `BookList` and pass `context` to it via `void _handleTap(BuildContext context)`. You will need to swap out your `onTap` to be something like:

```
onTap: () { _handleTap(context) }
```

If you're new to flutter then I highly recommend jumping on the `flutter/flutter` Gitter chat. Everyone there is super helpful and we hang out there as well.

**Comment by lukef** [comment]
Going to close this issue because it seems like it's working normally. I'll work to expand on the examples a little in the future.

**Comment by stemuk** [comment]
It works now, thanks a lot for your help!
