### ISSUE TITLE
Version 1.2.2 unreleased

### ISSUE THREAD

**Issue by Panthro** [goposse/fluro#34]
Hi guys

In the readme and everywhere states to use `1.2.2` but it looks like this version is not release, latest on https://pub.dartlang.org/packages/fluro is `1.2.1`

Was it released? Was a fail release? Or you just bumped the version for the next development iteration? Should bump the version in readme?

Sorry for the poor issue, but I guess you got me :-)

**Comment by diego-lipinski-de-castro** [comment]
+1

**Comment by SKLn-Rad** [comment]
+1 on this. Can't use this until the replacement fix is issued! (Unless I hook into the git directly in my yaml)

**Comment by lukef** [comment]
version 1.3.0 has now been published. sorry for the delay.
