### ISSUE TITLE
get param value on page

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [goposse/fluro#35]
I cannot figure out how i retrieve param vale in page

**Comment by lukef** [comment]
you will need to pass the value from the handler to your screen. 

The readme has an example:

```
var usersHandler = new Handler(handlerFunc: (BuildContext context, Map<String, dynamic> params) {
  return new UsersScreen(params["id"]);
});
```

If you want all the params you can push them all to the screen.

**Comment by diego-lipinski-de-castro** [comment]
Yes, this I know, but how I get them into the Widget, that's what I'm not sure yet

**Comment by lukef** [comment]
The example I posted above shows how to pass them into your screen widget. You will need to create a constructor for that widget that accepts the parameters. e.g.: 
```
final Map<String, dynamic> params;
UsersScreen(this.params);
```
Is this what you're asking?

**Comment by diego-lipinski-de-castro** [comment]
I think so, I was able to get the param using this, I think would be nice to complement the README example with something like this
