### ISSUE TITLE
Saving/restoring route stack when the app is paused/resumed.

### ISSUE THREAD

**Issue by paolosoares** [goposse/fluro#5]
Flutter doesn't implicitly persist the current route, which is annoying because every single app at some point will (or even should) do this.

Fluro could take care of this by saving the current route and, maybe, the entire current route stack when the app is paused and then restoring it when the application is resumed.

**Comment by alardizabal** [comment]
Hi @paolosoares. Can you tell me what your intended use case is for the above? I can take a look.

**Comment by lukef** [comment]
Closing for lack of information. The state of the application should be managed by Flutter (assuming the application wasn't killed). Feel free to re-open if you have more info.

**Comment by cgestes** [comment]
some more info.

see: https://github.com/littlerobots/flutter-native-state and https://github.com/flutter/flutter/issues/6827 that is currently being implemented in flutter.
