### ISSUE TITLE
cannot run the example

### ISSUE THREAD

**Issue by arashbi** [goposse/fluro#9]
When I try to run the example on ios, I get this error
```
 clang: error: no such file or directory: '/Users/arash/source/flutter-projects/fluro/example/ios/Runner/PluginRegistry.m'
    clang: error: no input files

```

**Comment by lukef** [comment]
Can you try running the app using the `flutter run` command? That file is generated by flutter.

**Comment by ride4sun** [comment]
Tried that - does not work...
C:\Projects\fluro2\example>flutter run
Running "flutter packages get" in example...          3.5s
Launching lib/main.dart on Android SDK built for x86 in debug mode...
The android gradle plugin version 2.4.0-alpha7 is too old, please update to the latest version.

To override this check from the command line please set the ANDROID_DAILY_OVERRIDE environment variable to "cffd81e9cbf9ceca9586b4f73996f8a29df7f87"

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Projects\fluro2\example\android\app\build.gradle' line: 15

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Could not create plugin of type 'AppPlugin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat app:properties
Running 'gradle assembleDebug'...
The android gradle plugin version 2.4.0-alpha7 is too old, please update to the latest version.

To override this check from the command line please set the ANDROID_DAILY_OVERRIDE environment variable to "cffd81e9cbf9ceca9586b4f73996f8a29df7f87"

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Projects\fluro2\example\android\app\build.gradle' line: 15

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Could not create plugin of type 'AppPlugin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1

C:\Projects\fluro2\example>

**Comment by ride4sun** [comment]
I get the same error in ItelliJ. After upgrading gradle I get another er

**Comment by ride4sun** [comment]
that app/src/build.gradle change works for me...

```
// flutter
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { stream ->
        localProperties.load(stream)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

flutter {
    source '../..'
}

// build versioning
def currentVersionCode() {
    def propsFile = file('versions.properties')
    def props = new Properties()
    props.load(new FileInputStream(propsFile))
    return props['build.versionCode'].toInteger()
}

def incrementVersionCode() {
    def propsFile = file('versions.properties')
    def props = new Properties()
    props.load(new FileInputStream(propsFile))
    def currentCode = props['build.versionCode'].toInteger()
    def nextCode = currentCode + 1
    props['build.versionCode'] = nextCode.toString()
    props.store(propsFile.newWriter(), null)
    return nextCode
}

// increments build version code on release builds
task('incrementVersionCode') << {
    incrementVersionCode()
}

tasks.whenTaskAdded { task ->
    if (task.name == 'assembleRelease') {
        task.dependsOn 'incrementVersionCode'
    }
}

buildscript {
    // application variables
    ext.app_ver_name = "1.0"

    // google version codes
    ext.build_tools_ver = '25.0.3'
    ext.support_lib_ver = '25.3.1'
    ext.google_play_ver = '10.2.4'
    ext.constraint_layout_ver = '1.0.2'
}

android {
    compileSdkVersion 25
    buildToolsVersion "$build_tools_ver"

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 25
        applicationId "com.goposse.routersample"
        versionCode currentVersionCode()
        versionName "$app_ver_name"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    compileOptions {
//        sourceCompatibility JavaVersion.VERSION_1_8
//        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // google
    compile "com.android.support:appcompat-v7:$support_lib_ver"
    compile "com.android.support:support-v13:$support_lib_ver"
    compile "com.android.support:support-v4:$support_lib_ver"

    // testing
    androidTestCompile "com.android.support:support-annotations:$support_lib_ver"
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test:rules:0.5'
	compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
}
repositories {
	maven {
		url 'http://dl.bintray.com/kotlin/kotlin-eap-1.1'
	}
}
```

**Comment by ride4sun** [comment]
in the app/build.gradle 

gradle version has to be changed to
classpath 'com.android.tools.build:gradle:2.2.3'

and 
gradleVersion = '2.2.3'

**Comment by lukef** [comment]
This issue should be fixed on master now thanks to @mit-mit. Let me know if you're still having problems.
